export const skillsLearned = [
    "Semantic & accessible HTML",
    "Error handling",
    "Git",
    "Responsive Web Design",
    "React",
    "GitHub Pull Request & Review",
    "JavaScript",
    "React Hooks",
    "NPM",
    "Working with API (fetch, axios)",
    "Redux (Toolkit)",
    "Immutability",
    "Promises, Async/Await",
    "Redux-Saga",
    "Markdown",
    "Debugging",
    "React Router",
    "Scrum",
    "CSS Flexbox",
    "CSS Grid",
    "Basic Figma",
    "Trello",
    "CSS BEM convention",
];

export const skillsWantLearn = [
    "JS classes",
    "Unit testing",
    "Node.js",
    "TypeScript",
    "Cypress",
    "React Context",
];